site_name: Unified Error Codes Specification
site_url: https://unified-error-codes.github.io/specification/
repo_url: https://github.com/unified-error-codes/specification
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    scheme: default
    primary: blue grey
  features:
    - content.action.edit

plugins:
  - macros
  - search
  - caption
  - add-number:
      order: 2

nav:
  - index.md

extra_css:
  - stylesheets/extra.css
